spring:
  application:
    name: raspberry
  datasource:
    url: jdbc:postgresql://localhost:5432/cmddev?currentSchema=cmddata
    username: cmddev
    password: cmddev

  flyway:
    enabled: true
    table: ms_changelog
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

schedule:
  #  runspeedtest:
  #    cron: 0 * * * * ?
  runping:
    cron: 0 * * * * ?

---
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:postgresql://192.168.1.3:5432/cmdpro?currentSchema=cmddata
    username: cmdpro
    password: cmdpro!1234

schedule:
#  runspeedtest:
#    cron: 0 0 * * * ?
  runping:
    cron: 0 * * * * ?
